### ISSUE TITLE
Can not install Jupyterlab extension

### ISSUE THREAD

**Issue by alitsaberi** [vidartf/ipydatetime#17]
I've tried to install `ipydatetime` using `pip`. When trying to install Jupyterlab extension, I get the following error:
`jupyter labextension install jupyter-widget-datetime`
```[LabBuildApp] Building in /Users/alisaberi/Desktop/gps-data-plotter/.venv/share/jupyter/lab
[LabBuildApp] Node v14.15.4

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (production, minimized)
[LabBuildApp] > node /Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.52s.

[LabBuildApp] > node /Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /Users/alisaberi/Desktop/gps-data-plotter/.venv/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.95s.

[LabBuildApp] > node /Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
[LabBuildApp] yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] Failed to load '/Users/alisaberi/Desktop/gps-data-plotter/.venv/share/jupyter/lab/staging/webpack.prod.minimize.config.js' config
[webpack-cli] Invalid options object. Module Federation Plugin has been initialized using an options object that does not match the API schema.
 - options.shared should be one of these:
   [non-empty string | object { <key>: object { eager?, import?, packageName?, requiredVersion?, shareKey?, shareScope?, singleton?, strictVersion?, version? } | non-empty string }, ...] | object { <key>: object { eager?, import?, packag$
   -> Modules that should be shared in the share scope. When provided, property names are used to match requested modules in this compilation.
   Details:
    * options.shared['jupyter-dataserializers'].import should be one of these:
      false | non-empty string
      -> Provided module that should be provided to share scope. Also acts as fallback module if no shared module is found in share scope or version isn't valid. Defaults to the property name.
      Details:
       * options.shared['jupyter-dataserializers'].import should be false.
         -> No provided or fallback module.
       * options.shared['jupyter-dataserializers'].import should be a non-empty string.
         -> A module that should be shared in the share scope.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "/Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "/Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/labapp.py", line 172, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/Users/alisaberi/Desktop/gps-data-plotter/.venv/lib/python3.8/site-packages/jupyterlab/commands.py", line 697, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

Also when I try to display `ipydatetime` widgets without installing the extension, I get the following:
`Loading widget...`

**Environment**

- Python 3.8.6
- Jupyterlab 3.1.12
- MacOS

**Comment by vidartf** [comment]
The widgets from this repo are now in the ipywidgets package (8.0.0), so closing these issues.
